### PR TITLE
fix issue with spaces in override values!?

### PR DESCRIPTION
**Pull request by cbikhazi**
#81 

Potential fix for this issue?

### CODE REVIEW

**Review by OliverMKing — APPROVED** [review]
LGTM

**Comment by maciej-ciach** [comment]
Can we get this fix merged and released as a new version, please? 

@davidgamero @JeannedArk @aamgayle @Vidya2606 @jaiveerk @nonylene

**Review by maciej-ciach — APPROVED** [review]

**Comment by nonylene** [comment]
you mention me but I'm just a external contributor, not a collaborator

**Review by jaiveerk — APPROVED** [review]

**Comment by cbikhazi** [comment]
@jaiveerk  - I have updated the commit to be signed. thanks

**Review by jaiveerk — APPROVED** [review]

**Pull request merged**
